version: "3"
services:
  app:
    tty: true
    image: node:12
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    ports:
      - 3000:3000
    command: bash -c "npm install; npm run start"
    networks:
      - the_net
networks:
  the_net:
    driver: bridge
